# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Query": "00_core.ipynb",
         "Results": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://vegabj.github.io/nbdev_test/"

git_url = "https://github.com/vegabj/nbdev_test/tree/master/"

def custom_doc_links(name): return None
