# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/00_core.ipynb (unless otherwise specified).

__all__ = ['Query', 'Results']

# Cell
class Query:
    def __init__(self, cluster: str="<cluster_name>", db: str="<db_name>"):
        self.kcsb = KustoConnectionStringBuilder(cluster).from_interactive_authentication()
        self.db = db
        self.client = KustoClient(self.kcsb)
    def __repr__(self):
        return self.kcsb
    def query(query_string: str):
        return self.client.execute(self.db, query_string)

# Cell
class Results:
    def __init__(self):
        pass
    def get_results(self):
        pass #do some pretty printing of results